### ISSUE TITLE
Image viewer only loads thumbnails

### ISSUE THREAD

**Issue by buccalon** [tropy/tropy-plugin-iiif#1]
@inukshuk thanks for this plugin!

Should I expect a high-resolution image viewer at this point?
As a suggestion, you might consider ["dezoomifying"](https://dezoomify.ophir.dev/) images for hd photo import.

Manifest: http://ddsnext.crl.edu/services/item/manifest/2053
Expectation: High resolution image viewer
Results: Tropy only loads thumbnails

<img width="797" alt="image" src="https://user-images.githubusercontent.com/476699/161570853-4f966bc9-166c-424e-b2b2-366c9dd15919.png">

**Comment by inukshuk** [comment]
Currently the plugin should fetch the full image, but I might have misunderstood the way the image API is used here. In the manifest, the resource's id is:

http://images.crl.edu/loris/e5/cb/a5/f2/-a/6d/c-/44/02/-a/42/d-/c8/c5/84/a4/e1/02/000002.tiff/full/800,/0/default.jpg

Which I guess in this case is the image you would want to fetch, right?

But the plugin currently also checks the `service` section, which in this case links to:

http://ddsnext.crl.edu/services/image/246235

And the plugin therefore tries this URL first:

http://ddsnext.crl.edu/services/image/246235/full/full/0/default.jpg

However, here this redirects to:

http://images.crl.edu/loris/e5/cb/a5/f2/-a/6d/c-/44/02/-a/42/d-/c8/c5/84/a4/e1/02/000002.tiff/full/90,/0/default.jpg

It looks to me like this redirect is wrong?

**Comment by buccalon** [comment]
@inukshuk you're right, and this is a [2018 implementation](https://www.youtube.com/watch?v=bBhWp748_sQ) in which [they don't publicize the manifest link](http://ddsnext.crl.edu/titles/108)

I imported another manifest from BnF which worked fine: https://gallica.bnf.fr/iiif/ark:/12148/btv1b85530100/manifest.json

The only issue I had was that many pages had to be consolidated after importing

<img width="840" alt="image" src="https://user-images.githubusercontent.com/476699/161655918-ef5bbcf8-e80e-40ba-b741-786ca2a61b89.png">

I clicked each warning icon individually, but I assume that "consolidate item" pile them up in the same process

<img width="309" alt="image" src="https://user-images.githubusercontent.com/476699/161658136-f8c315eb-2955-4d58-ba3e-2437f22a90b7.png">

I also tried to import two version 3.0 manifests I know were statically generated, but neither worked:

- https://nomad-project.co.uk/objects/collection/gold-broach/index.json
- https://imaginerio-images.s3.us-east-1.amazonaws.com/iiif/2589099/manifest.json

Using Tropy to annotate IIIF manifests will be a game-changer for research, thanks again for this!

**Comment by inukshuk** [comment]
We haven't implemented version 3.0 yet, partly because we had not seen any archives using it, I'll make a note of your links, thanks!

As for the consolidation, this is the expected behavior: when you import the manifest, Tropy does not immediately try and download all images at once, it just creates the respective records in the database. The images are later loaded on demand when you actually access them in the UI. Instead of clicking on the warning icons, you can quickly scroll all the way to the bottom in the item's photo panel -- this should make Tropy download all the photos which are not in the image cache yet in one go.
